@startuml
package entity {
    struct User {
        + userId : UUID v7 (PK)
        --
        * username : string (unique)
        * accountName : string
        * updatedAt : timestamp
    }
}

package repository {
    interface IUserRepository {
        Create(ctx context.Context, user *entity.User) (uuid.UUID, error)
    }
    struct UserRepository {
        Create(ctx context.Context, user *entity.User) (uuid.UUID, error)
    }
}

package usecase {
    interface IUserUsecase {
        Execute(ctx context.Context, username string, accountName string) (uuid.UUID, error)
    }
    struct UserUsecase {
        Execute(ctx context.Context, username string, accountName string) (uuid.UUID, error)
    }
}

entity.User --o repository.IUserRepository : depends on
repository.IUserRepository <|.. repository.UserRepository : implements
repository.IUserRepository --o usecase.IUserUsecase : depends on
usecase.IUserUsecase <|.. usecase.UserUsecase : implements
@enduml