@startuml

entity "user" as User {
    + user_id : uuid v7 (PK)
    --
    * username : string (unique)
    * account_name : string
    * updated_at : timestamp
}

entity "user_profile" as UserProfile {
    + profile_id : uuid (PK)
    --
    * user_id : uuid (FK)
    * user_icon_url : string
    * home_image_url : string
    * introduction : string
    * cover_image_url : string
}


User ||--|| UserProfile
@enduml