// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interfaces/createUser.go
//
// Generated by this command:
//
//	mockgen -source=./usecase/interfaces/createUser.go -destination=./test/mocks/usecase/createUser.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockICreateUserUsecase is a mock of ICreateUserUsecase interface.
type MockICreateUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockICreateUserUsecaseMockRecorder
	isgomock struct{}
}

// MockICreateUserUsecaseMockRecorder is the mock recorder for MockICreateUserUsecase.
type MockICreateUserUsecaseMockRecorder struct {
	mock *MockICreateUserUsecase
}

// NewMockICreateUserUsecase creates a new mock instance.
func NewMockICreateUserUsecase(ctrl *gomock.Controller) *MockICreateUserUsecase {
	mock := &MockICreateUserUsecase{ctrl: ctrl}
	mock.recorder = &MockICreateUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreateUserUsecase) EXPECT() *MockICreateUserUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockICreateUserUsecase) Execute(ctx context.Context, username, accountName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, username, accountName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockICreateUserUsecaseMockRecorder) Execute(ctx, username, accountName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockICreateUserUsecase)(nil).Execute), ctx, username, accountName)
}
