lint:
	golangci-lint run

dev:
	@echo "Building dev stage"
	docker compose -f docker-compose.dev.yml up --build

test stage:
	@echo "Building test stage"
	docker compose -f test-docker-compose.yml up --build