services:
  backend:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: development 
    ports:
      - '8080:8080'
    env_file:
      - ./config/.env 
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./config/.env 
    volumes:
      - ./data/db:/var/lib/postgresql/data