@startuml
entity "user_security" as UserSecurity {
    + user_id : uuid (FK → users.user_id)
    --
    * password_hash : string
    * password_updated_at : timestamp
    * last_login_at : timestamp
}
@enduml