@startuml
entity "auth_security" as UserSecurity {
    + authID : uuid
    --
    * userID : uuid(FK → users.user_id)
    * provider : enum
    * password_hash : string
    * password_updated_at : timestamp
    * last_login_at : timestamp
}
@enduml